### ISSUE TITLE
`tile` moves the terminal window that I run it from.

### ISSUE THREAD

**Issue by emctague** [grocid/gtile#1]
Hi, I've tried using gtile, but I can't get it to move anything other than the terminal window that I run it from. I've also tried running it while focused on a different window (e.g. via the alt+f2 runner interface) and that doesn't work, either.

Here's an example:

![example](https://user-images.githubusercontent.com/22970065/30243418-9ce76ab2-9576-11e7-9fa8-bc240da89e9f.gif)

Is this the intended behavior and I'm just not understanding how to use it, or is it not working properly on my machine?

**Comment by grocid** [comment]
Hi!

The first behaviour is intended, i.e., it is indeed the window being in focus that is supposed to be tiled. The second behaviour is not. If you have a windowed focused and you press a hotkey that does not alter WM focus, it should move the intended window. You could try binding any `xdotool` command to that hotkey and see if the problem persists. E.g.

```xdotool getactivewindow windowsize 100 100 windowmove 0 0```

Moreover, I noticed that `tile 6` did not produce the correct window size. I don't know why this is the case, I am not able to reproduce it with a freshly cloned version.

**Comment by emctague** [comment]
I think it might be because I have a 2-monitor setup, and I modified the script slightly to retrieve display size dynamically using Tk, so it's giving the sum of both. Would probably be fine with only one monitor.

The second behavior, by the way, was because I was trying from MATE's alt+f2 menu, which removes focus from the active window. I fixed it by making an actual keybinding.
